### PR TITLE
studio: svg waves for deck or slide background

### PR DESCRIPTION
**Pull request by hjades**
## PR Checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes

## Other information

PR is still work in progress, but available for review. it's my first time adding features, your review and suggestions will be very helpful, thank you!

TODO:
- [ ] Add color options
- [ ] Refine UI

Issue Number: #874

### CODE REVIEW

**Comment by peterpeterparker** [comment]
WOW! That's really, really cool @hjades 🤩

So far all good to me. There are one or two issues with the integration of the results, the `background` slot, but don't loose time with that, I will help and take care of the integration. What's important is  the SVG generation which looks AWESOME!

If you can add the color picker for me it's all good.

**Comment by peterpeterparker** [comment]
P.S.: Not related ...

- Are you interested by some stickers? If yes, send me a PM with your address, happy to send you some in November

- Do you have a Twitter account? Will probably tweet about the feature afterwards and happy to tag you

**Comment by hjades** [comment]
hi! added the color picker~

here are the screenshots
Screen Shot 2020-10-11 at 19 07 37
Screen Shot 2020-10-11 at 19 08 32
[Screen Recording 1](https://drive.google.com/file/d/1-Xfn1K3H58wJGkQmWFOr0D_OVekhaBUW/view?usp=sharing)
[Screen Recording 2](https://drive.google.com/file/d/1KoDRXiDsTMUViJLxgmdJmTu8R8bTmZFV/view?usp=sharing)

yup! i would love some stickers~
oh thanks!! my twitter is `@jadesuntoro` 🙆🏻‍♀️

**Comment by peterpeterparker** [comment]
Awesome work @hjades! Thanks a lot 🙏.

As discussed, I'll do the integration (routing, background slots etc.) in #952.

Will tweet about it  once done within next days.

P.S.: Cool send my your address on slack or email  for the stickers, will send some in November

**Pull request merged**
