### PR TITLE
(fix) updates to new medium profile URL

### LINKED ISSUE #959: social: medium has changed their profile urls
### Affected part of DeckDeckGo

- [X] Web Components

### Feature Description

The [social](https://docs.deckdeckgo.com/components/social/) web component is used in the template author to automatically parse logo and more important link to social url.

For example if used as following, a link to twitter with the correct url format `https://twitter.com/daviddalbusco` will be rendered.

```
<deckgo-social twitter="daviddalbusco">
  <ion-icon slot="icon" name="logo-twitter"></ion-icon>
</deckgo-social>
```

This works  like  a charm. Now, I just noticed that Medium did change the user's  profile url.

Was: `https://medium.com/@david.dalbusco`

New: `https://daviddalbusco.medium.com/`

The goal of this feature  is therefore to update the Medium URL in the [Social component](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/social) source code.

### Get Started

If you need help to get started with this feature, I'll be happy to help.

Ping me: @peterpeterparker | [twitter](https://twitter.com/daviddalbusco) | [email](mailto:david.dalbusco@outlook.com) | [slack](https://join.slack.com/t/deckdeckgo/shared_invite/enQtNzM0NjMwOTc3NTI0LTBlNmFhODNhYmRkMWUxZmU4ZTQ2MDJiNjlmYWZiODNjMDU5OGRjYThlZmZjMTc5YmQ3MzUzMDlhMzk0ZDgzMDY)

### PR DESCRIPTION
**Pull request by sai-github**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes

## Other information

Issue Number: Fixes #959 , but introduces breaking changes to some medium profiles

### CODE REVIEW

**Comment by sai-github** [comment]
I have made some unrelated changes due to my code formatter, I will remove the changes

**Comment by sai-github** [comment]
Can I also make changes at https://docs.deckdeckgo.com/components/social/#app-components-social-attributes for medium attribute ?

**Comment by peterpeterparker** [comment]
Awesome! Sure if you can also update the doc it's super 👍

**Comment by peterpeterparker** [comment]
@sai-github not sure here, are  you waiting on me or should I merge this one? not sure I can as it is displayed as being a draft...

**Comment by sai-github** [comment]
I will make the docs change and remove it from draft .. you can take a call on merging it

**Comment by sai-github** [comment]
How can I generate docs to view my changes ?

**Comment by peterpeterparker** [comment]
@sai-github cool! `npm ci && npm run start` or `npm ci && npm run build` in [docs](https://github.com/deckgo/deckdeckgo/tree/master/docs)

**Comment by sai-github** [comment]
When I try to run I get the following error
```
[ ERROR ]  Node Polyfills Required
           For the import "https" to be bundled from ./node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js, ensure
           the "rollup-plugin-node-polyfills" plugin is installed and added to the stencil config plugins. Please see
           the bundling docs for more information. Further information: https://stenciljs.com/docs/module-bundling
```

Should I install any other dependency globally ?

**Comment by peterpeterparker** [comment]
@sai-github you are on windows? it might be related but, no worries, I'll take care of the build, looks good to me 👍 

thx a lot for the PR and help!!!

if you would like to get some stickers, drop me a PM with your address, happy to send you some in a couple of weeks :)

**Pull request merged**
