### PR TITLE
site: added menu close button

### PR DESCRIPTION
**Pull request by saideepesh000**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes

## Other information

This PR adds a close button for the menu bar

## Gif
close-btn

Issue Number: #1047

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Looks  good to me. Design and feature are these expected 👍.

You can maybe just remove the `className="close"`? Not sure but, I think it isn't use right?

**Comment by saideepesh000** [comment]
> 
> 
> Looks good to me. Design and feature are these expected 👍.
> 
> You can maybe just remove the `className="close"`? Not sure but, I think it isn't use right?

@peterpeterparker, lol, I forgot to remove it, w'll do that

**Comment by peterpeterparker** [comment]
cool, thx. you can remove the draft and I'll merge it.

**Comment by saideepesh000** [comment]
@peterpeterparker, done 👍

**Comment by peterpeterparker** [comment]
thank you for the PR @saideepesh000 👍

**Pull request merged**
