### PR TITLE
play button position fixed

### PR DESCRIPTION
**Pull request by MehulG**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes

## Other information

Issue Number: N/A

### CODE REVIEW

**Review by peterpeterparker — CHANGES_REQUESTED** [review]
Thx for the PR. 

- please revert the package-lock.json change

- the css works partially, it probably need more improvements to be perceptively responsive. can you try to improve the positioning?

**Comment by MehulG** [comment]
Hey @peterpeterparker , I did make a few changes and reverted package-lock.json. Can you take a look at it?

**Comment by peterpeterparker** [comment]
thx for the improvements @MehulG appreciated

unfortunately it still doesn't achieve to be responsive. the goal is to stick the "play" button right in the  center x/y of the previous and next buttons. maybe my first mockup wasn't clear enough, sorry for that. here some more in comparison to your implementation:

Capture d’écran 2020-11-06 à 17 10 27
Capture d’écran 2020-11-06 à 17 10 32
Capture d’écran 2020-11-06 à 17 10 38
Capture d’écran 2020-11-06 à 17 10 42

**Comment by MehulG** [comment]
Hey! There was a slight misunderstanding in the requirements. I reconfigured the CSS to make the position at center of next and prev buttons. and It is now working perfectly. Can you @peterpeterparker review it once now? I hope it satisfies the conditions :)

**Comment by peterpeterparker** [comment]
Awesome @MehulG 👍 sorry for the misunderstanding and thanks a  lot for the multiple improvements, looks super now! Really cool 😃

P.S.: If you want some stickers, send me your address through PM, happy to send you some per post

**Pull request merged**
