### PR TITLE
split vertical text alignment

### PR DESCRIPTION
**Pull request by boradakash**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes

## Other information

Issue Number: https://github.com/deckgo/deckdeckgo/issues/679

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Thx for the PR 👍 

Will look at it asap.

**Comment by peterpeterparker** [comment]
@boradakash I think you are right, it's the correct utils to modify in order to solve this issue. 

even though your PR solve it too, I would suggest the following if you are agree. Instead of specifying a style if "not vertical" we remove the style for both "not vertical and vertical" and then set a set for "vertical".

Like:

```
deckgo-slide-split > *[slot="start"],
deckgo-slide-split > *[slot="end"] {
  display: flex;
  flex-direction: column;
  align-items: center; // <--------- Remove this
  justify-content: center;
  word-break: break-word;
  text-align: center; // <--------- Remove this
}
```

And then your code but without the "not:" and with "center":

```
deckgo-slide-split:[vertical] > *[slot="start"],
 deckgo-slide-split:[vertical] > *[slot="end"] {
   align-items: center;
    text-align: center;
 }
```

Doing so we spare ... one line 🤣

What do you think, is that too much or? If agree, can you update your branch/PR?

**Comment by boradakash** [comment]
@peterpeterparker Agreed.
I've updated PR.
I thought doing that way will break some places which I couldn't be aware of.
That's why I've made it other way by `:not[vertical]`
But your solution is perfect :)

**Comment by peterpeterparker** [comment]
Super! I'll merge it later this evening. Have a nice day :)

**Comment by peterpeterparker** [comment]
Awesome, thx for the PR @boradakash 👍

**Pull request merged**
