### PR TITLE
Preserve aspect ratio when resizing and click shift key

### PR DESCRIPTION
**Pull request by Edgar160**
Preserve aspect ratio when resizing and clicking the shift keyboard button

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes

## Other information

Issue Number: N/A

### CODE REVIEW

**Comment by peterpeterparker** [comment]
thx for the PR @Edgar160 

it's a cool idea but, when I try your PR, the results are surprising. Maybe I do something wrong?

I'm on a mac, in this gif I hold "left shift" and resize with the mouse.

ezgif com-video-to-gif(2)

**Comment by Edgar160** [comment]
That's funny, in my local it behaves different, can you try to resize only on the vertical and horizontal lines instead of in the corners?

**Comment by peterpeterparker** [comment]
It does the following when I resize border (while still holding left 

ezgif com-video-to-gif(3)
shift)

**Comment by Edgar160** [comment]
that's not expected :(, i did some other custom changes, maybe those are making this changes working properly(although i don't know why) i why try to replicate and fix it
Regards

**Comment by peterpeterparker** [comment]
super! keep me posted and thx again 👍

**Comment by peterpeterparker** [comment]
This PR has been open for a while, I guess it is no more active, therefore I close it.
Of course, if this assumption would be wrong, let me know, I would be happy to reopen it!

**Pull request closed without merging**
