### PR TITLE
Feat: spanish translation and typo fixes

### PR DESCRIPTION
**Pull request by mauriciolanda4**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Feature

## Other information

Issue Number: N/A

### CODE REVIEW

**Comment by mauriciolanda4** [comment]
This is good enough for a start 😄

**Comment by peterpeterparker** [comment]
Wow that's awesome 🤩

Muchas gracias @mauriciolanda4 🙏

I'll now develop the language detection and also add it to the settings and release afterwards!

You've got Twitter? I would be happy to tag you for credits when I tweet about it.

**Comment by mauriciolanda4** [comment]
I do not have a twitter, yet i have a linkedin, you could add that if you wish

**Comment by peterpeterparker** [comment]
Will link your Github account 👍

**Pull request merged**
