### PR TITLE
fix(sign-in-button): add tabindex

### PR DESCRIPTION
**Pull request by StefanNieuwenhuis**
CLOSES: #534

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes

## Other information

Issue Number: 534

### CODE REVIEW

**Comment by peterpeterparker** [comment]
@StefanNieuwenhuis could you revert the method `signIn`.

I think that we have to keep it as displayed in master.

User (without being registered) could create a presentation to try it out. Therefore they land on the path `/editor/:id` that's why the method is there, to keep track of the presentation they would have created in case they log in.

(Test editor -> user anonymous -> writer 1 or 2 slides -> login -> comeback -> previous deck with id has to be transferred to newly created user)

**Comment by StefanNieuwenhuis** [comment]
> @StefanNieuwenhuis could you revert the method `signIn`?
> 
> I think that we have to keep it as displayed in master.
> 
> User (without being registered) could create a presentation to try it out. Therefore they land on the path `/editor/:id` that's why the method is there, to keep track of the presentation they would have created in case they log in.
> 
> (Test editor -> user anonymous -> writer 1 or 2 slides -> login -> comeback -> previous deck with id has to be transferred to newly created user)

Ah, I understand! Then we should definitely keep this method, but I don't understand why it renders to an `<a/>` in stead of an `<ion-route/>`...Can you explain that to me?

**Comment by peterpeterparker** [comment]
@StefanNieuwenhuis I'm not sure but spontaneously I would say because I wasn't able to attach a click event on an `ion-router-link` respectively there is no such prop to pass the click till the shadowed `a`. Might be wrong too, just a vague flashback ;)

**Comment by peterpeterparker** [comment]
@StefanNieuwenhuis I had a quick test and it turned out that adding `tabindex={0}` on the elements where the tab was missing was enough to solve the related issue. 

As I was planing to transform the `a` into `button` (to add "enter" support) I added the index at the same time in PR https://github.com/deckgo/deckdeckgo/pull/628

That's why I allow myself to close this issue without merging it, I hope it's cool?

**Pull request closed without merging**
