### PR TITLE
enhancement(markdown): updating markdown worker to identify width and height

### PR DESCRIPTION
**Pull request by grantlouisherman**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ 👎 ] Tests for the changes have been added (for bug fixes / features)
- [ 👎 ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?
Updated the functionality of the of the markdown worker to look for width and height for images. If width and height exists then it will add those measurements to the deck deck go img and return. 

- [ X] Feature

## Other information

Issue Number: 1007

### CODE REVIEW

**Comment by peterpeterparker** [comment]
@grantlouisherman thank you, looks super to me!

I just have one question which popped up in my mind while using it: should we use `=` or `:` as separator respectively for example `width=100px,height=100px` or `width:100px,height:100px`?

`=` sounds like attributes but `:` is closer to CSS, if we enhance it  in the future, maybe  `:` is better?  what do you think?

beside that, also note that  your  implementation can / should replace (breaking changes) the current parser. Therefore  you can delete the [current regex](https://github.com/deckgo/deckdeckgo/blob/1eff4731f2881a985e397e85e2017ee86eff3aac/webcomponents/markdown/src/components/workers/utils/markdown-img.utils.ts#L10), update these [examples](https://github.com/deckgo/deckdeckgo/blob/1eff4731f2881a985e397e85e2017ee86eff3aac/webcomponents/markdown/src/components/workers/utils/markdown-img.utils.ts#L4) and update the examples in [index.html](https://github.com/deckgo/deckdeckgo/blob/master/webcomponents/markdown/src/index.html)

**Comment by grantlouisherman** [comment]
hey @peterpeterparker so I added an or statement so then the user can decide which method they want to use. So just so I'm clear you want to remove your current regex to be replaced by the width/height stuff. So moving forward you want the user to input height and width in the format of `height(= | :) 100px width(= | :)200px`

**Comment by peterpeterparker** [comment]
@grantlouisherman no need to add a statement, your code is the new default, you can/should remove the current regex. we only are going to support what you implemented.

i was thinking that maybe `:` is better than `=`. there too only one method, but I was asking the one you rather like?

**Comment by grantlouisherman** [comment]
Gotcha @peterpeterparker then yeah I would have to agree that `:` is more consistent with styling. Let me update.

**Comment by peterpeterparker** [comment]
awesome! thx a lot for the PR 👍

**Pull request merged**
